version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run: make build-ci
      - run: make test
      - persist_to_workspace:
          root: .
          paths: [dist/server]

  publish:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run: ./docker_deploy.sh escaletech/tog-session-server

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test:
          filters: &ci-filters { tags: { ignore: /.*/ } }
  release:
    jobs:
      - build-and-test:
          filters:
            &release-filters {
              branches: { ignore: /.*/ },
              tags: { only: /^v.*/ },
            }
      - publish:
          requires:
            - build-and-test
          filters: *release-filters
