version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0
  aws-eks: circleci/aws-eks@1.1
  gh-release: escaletech/gh-conventional-release@0.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.14
    steps:
      - checkout
      - run: make build-ci
      - run: make test
      - persist_to_workspace:
          root: .
          paths: [dist/server]

ci_only: &ci_only
  filters:
    tags: { ignore: /.*/ }

staging_only: &staging_only
  filters:
    branches: { only: [master] }
    tags: { ignore: /.*/ }

release-filters: &release-filters
  filters:
      branches: { ignore: /.*/ }
      tags: { only: /^v.*/ }

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test:
          <<: *ci_only

  staging:
    jobs:
      - build-and-test:
          <<: *staging_only
      - aws-ecr/build-and-push-image:
          context: eks-apps-escale-staging
          repo: tog-session-server
          create-repo: true
          attach-workspace: true
          tag: ${CIRCLE_SHA1:0:7},master
          dockerfile: Dockerfile
          requires: [build-and-test]
          <<: *staging_only

  release:
    jobs:
      - build-and-test:
          <<: *release-filters
      - aws-ecr/build-and-push-image:
          context: eks-applications
          repo: tog-session-server
          create-repo: true
          attach-workspace: true
          tag: ${CIRCLE_TAG#v},latest
          dockerfile: Dockerfile
          requires: [build-and-test]
          <<: *release-filters
      - gh-release/create-release:
          context: github-create-release
          requires: [aws-ecr/build-and-push-image]
          <<: *release-filters

