version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test

  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install --production
      - run: docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run: ./docker_deploy.sh escaletech/tog-session-server

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters: &ci-filters { tags: { ignore: /.*/ } }
  release:
    jobs:
      - test:
          filters:
            &release-filters {
              branches: { ignore: /.*/ },
              tags: { only: /^v.*/ },
            }
      - publish:
          requires:
            - test
          filters: *release-filters
